Migrate images to server
Xivis/poap pull request #25
Opened 2019-10-17 17:09 UTC by frandelgado

This PR adds all of the event's badge images to the /website/public/events/badges/ folder.
all migrated images have their names set to {fancy-id}.{extension}
Note that the event with id 30 does not have a fancy-id so it could not be migrated with a valid name.

In order to update the database to point to the new images, the following sql sentences should be executed:
https://gist.github.com/frandelgado/2ef83f3ef05f2057942eff044eaa939c

The script used to generate the images and the migration file can be found at:
https://gist.github.com/frandelgado/ed14f2ce83cbb935f7cbb8be17355078

2019-10-17 20:20 UTC, ragonzal commented
@frandelgado there ir a committed file `.png`, why?
Did we run any validation comparing: amount of events in API, amounts of `UPDATE` statements, amount of files in folder?

2019-10-17 20:20 UTC, ragonzal requested changes
@frandelgado there ir a committed file `.png`, why?
Did we run any validation comparing: amount of events in API, amounts of `UPDATE` statements, amount of files in folder?

2019-10-18 13:03 UTC, frandelgado commented
Right, I left it because even though there was no fancy id for it I still wanted to keep the image in the migration. 
I changed the name to a more sensible one (the one it previously had) and updated the gist to match that name.

2019-10-21 14:42 UTC, ragonzal approved these changes

2019-10-21 14:42 UTC, merged